# Generated by Django 4.1.3 on 2022-11-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0003_patient_gender_alter_patient_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Nakuru', 'Mombasa'), ('Nakuru', 'Nakuru'), ('Kisumu', 'Kisumu')], max_length=255, null=True)),
            ],
        ),
    ]
