# Generated by Django 4.1.3 on 2022-11-21 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0007_alter_doctor_options_remove_doctor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookingapp.county'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('Dermatology', 'Dermatology'), ('Family Medicine', 'Family Medicine'), ('Internal Medicine', 'Internal Medicine'), ('Neurosurgery', 'Neurosurgery'), ('Gynaecology', 'Gynaecology'), ('Oncology', 'Oncology'), ('Paediatrics', 'Paediatrics'), ('Psychiatry', 'Psychiatry'), ('Urology', 'Urology'), ('Public Health', 'Public Health')], max_length=50, null=True),
        ),
    ]
