# Generated by Django 4.1.3 on 2022-11-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0011_doctor_has_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='biography',
            field=models.TextField(default='-', null=True),
        ),
    ]
