# Generated by Django 4.1.3 on 2022-11-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0012_doctor_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='county',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Nakuru', 'Nakuru'), ('Kisumu', 'Kisumu')], max_length=255, null=True),
        ),
    ]
