# Generated by Django 4.1.3 on 2022-12-04 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookingapp', '0014_alter_doctor_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Emergency Specialist', 'Emergency Specialist'), ('Allergy Specialist', 'Allergy Specialist'), ('Anesthesiologist', 'Anesthesiologist'), ('COlon and Rectal Surgeon', 'COlon and Rectal Surgeon'), ('Consultant', 'Consultant')], max_length=50)),
                ('biography', models.TextField(default='-', null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.county')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_registration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
